"""Build small country-boundary data from official Natural Earth GeoJSON.

Requires Shapely. Inputs: index.html, countries GeoJSON, disputed-areas GeoJSON.
Original coastline deviation is <0.01 degrees; grading keeps a 12 km guard.
"""
import hashlib
import json
import re
import sys
from pathlib import Path
from shapely import make_valid, set_precision
from shapely.geometry import Point, mapping, shape

repo = Path(__file__).resolve().parents[1]
source, disputed_source = map(Path, sys.argv[1:3])
html = (repo / 'index.html').read_text()
datasets = {k: json.loads(v) for k, v in re.findall(r'<script id="([^"]+)" type="application/json">(.*?)</script>', html, re.S)}
countries = [dict(it, geometry=datasets['geometryData']['items'].get(it['id'], it['geometry']))
             for it in datasets['auditData'] if it['section'] == '국가 98']
countries += [it for it in datasets['contentData']['items'] if it['topic'] == 'country']
features = json.loads(source.read_text())['features']
features = [(shape(f['geometry']), f['properties']) for f in features]

def polygons(geom):
    # Keep holes, offshore islands and microstates; repair source topology first.
    if not geom.is_valid:
        geom = make_valid(geom)
    if geom.geom_type == 'GeometryCollection':
        return [p for part in geom.geoms if part.geom_type in ('Polygon', 'MultiPolygon') for p in polygons(part)]
    geom = set_precision(geom, 0.00001)
    if geom.area > 0.1:
        geom = geom.simplify(0.01, preserve_topology=True)
    coords = mapping(geom)
    p = coords['coordinates'] if coords['type'] == 'MultiPolygon' else [coords['coordinates']]
    return [[[[round(x, 5), round(y, 5)] for x, y in ring] for ring in poly] for poly in p]

out = {'source': 'Natural Earth 1:10m admin-0 countries and disputed areas',
       'sourceUrl': 'https://github.com/nvkelso/natural-earth-vector/tree/master/geojson',
       'sourceSha256': hashlib.sha256(source.read_bytes()).hexdigest(),
       'disputedSha256': hashlib.sha256(disputed_source.read_bytes()).hexdigest(),
       'simplificationDegrees': 0.01, 'byName': {}, 'disputed': []}
for it in countries:
    g = it['geometry']
    matches = [(poly, props) for poly, props in features if poly.covers(Point(g['lon'], g['lat']))]
    assert len(matches) == 1, (it['name'], [props['ADMIN'] for _, props in matches])
    poly, props = matches[0]
    out['byName'][it['name']] = {'code': props['ADM0_A3'], 'polygons': polygons(poly)}
    assert shape({'type': 'MultiPolygon', 'coordinates': out['byName'][it['name']]['polygons']}).is_valid, it['name']
for f in json.loads(disputed_source.read_text())['features']:
    out['disputed'].extend(polygons(shape(f['geometry'])))
def pack_ring(ring):
    encoded, prior = [], [0, 0]
    for point in ring:
        for axis in range(2):
            current = round(point[axis] * 100000)
            delta = current - prior[axis]
            prior[axis] = current
            value = ~(delta << 1) if delta < 0 else delta << 1
            while value >= 32:
                encoded.append(chr(((value & 31) | 32) + 63))
                value >>= 5
            encoded.append(chr(value + 63))
    return ''.join(encoded)

for boundary in out['byName'].values():
    boundary['polygons'] = [[pack_ring(ring) for ring in poly] for poly in boundary['polygons']]
out['disputed'] = [[pack_ring(ring) for ring in poly] for poly in out['disputed']]
payload = json.dumps(out, ensure_ascii=False, separators=(',', ':'))
decoder = ('function ring(s){var p=[],v=[0,0],i=0;while(i<s.length){for(var k=0;k<2;k++){var n=0,b,t=0;do{b=s.charCodeAt(i++)-63;n|=(b&31)<<t;t+=5;}while(b>=32);v[k]+=(n&1)?~(n>>>1):n>>>1;}p.push([v[0]/1e5,v[1]/1e5]);}return p;}'
           'function unpack(ps){return ps.map(function(p){return p.map(ring);});}'
           'Object.keys(d.byName).forEach(function(n){d.byName[n].polygons=unpack(d.byName[n].polygons);});d.disputed=unpack(d.disputed);')
(repo / 'assets/country-boundaries.js').write_text('/* Natural Earth public-domain boundaries; generated by scripts/build-country-boundaries.py. */\n' +
    '(function(r){var d=' + payload + ';' + decoder + 'if(typeof module==="object"&&module.exports)module.exports=d;else r.WGCountryShapes=d;})(typeof globalThis!=="undefined"?globalThis:this);\n')
print(json.dumps({'countries': len(out['byName']), 'disputedParts': len(out['disputed']), 'bytes': len(payload.encode())}))
